name: nom_repositori_workflow

on:
  push:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

  cypress_job:
    needs: linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Tests Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        continue-on-error: true

      - name: Save Cypress results
        run: echo "success" > result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: result.txt

  add_badge_job:
    needs: cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cypress-results

      - name: Update README with badge
        run: |
          OUTCOME=$(cat result.txt)
          if [ "$OUTCOME" == "success" ]; then
            BADGE="![Success](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)"
          else
            BADGE="![Failure](https://img.shields.io/badge/test-failure-red)"
          fi
          echo "\nRESULTAT DELS ÚLTIMS TESTS\n$BADGE" >> README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "alemeco2005@gmail.com"
          git add README.md
          git commit -m "Update README with test results badge"
          git push

  deploy_job:
    needs: cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: Bw08urjkULZ7EFjM5E0oMGlb 
          vercel-args: "--prod"

  notification_job:
    needs: [linter_job, cypress_job, add_badge_job, deploy_job]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification Email
        run: |
          echo "S'ha realitzat un push en la branca main..." | mail -s "Resultat del Workflow" ${{ secrets.EMAIL_SECRET }}

