on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install
          npm run build

      - name: Ejecutar tests de Cypress
        run: |
          npx cypress run --record

      - name: Subir artefacto con el resultado del test
        uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: ./result.txt

  add_badge_job:
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Recuperar artefacto
        uses: actions/download-artifact@v4
        with:
          name: result.txt

      - name: Settegem l´ixida
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: cypress_outcome

      - name: Afegir el badge del resultat del test
        uses: ./.github/actions/resultat_test_action
        with:
          resultats_test: ${{ steps.cypress_outcome.outputs.cypress_outcome }}

      - name: Commit i push dels canvits
        uses: EndBug/add-and-commit@v9
        with:
          add: . 
          author_name: "Kike Valero"
          author_email: "kvalerosor@hotmail.com"
          message: "Resultat test badge"
          push: true

  deploy_job:
    runs-on: ubuntu-latest
    needs:
      - add_badge_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=$VERCEL_TOKEN --yes

  notification_job:
    needs: [linter_job, cypress_job, add_badge_job, deploy_job]
    runs-on: ubuntu-latest
    steps:
      - name: Install mail utilities
        run: sudo apt-get install -y mailutils

      - name: Send Notification Email
        run: echo "S'ha realitzat un push en la branca main..." | mail -s "Resultat del Workflow" ${{ secrets.EMAIL_SECRET }}
