on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true

        id: cypress
      - name: Save Cypress results
        run: echo ${{steps.cypress.outcome}} > result.txt

      - name: Upload Cypress results artifact
        uses: actions/upload-artifact@v3
        with:
          name: resultats_test
          path: result.txt

  add_badge_job:
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Cypress Test Artifacts
        uses: actions/download-artifact@v3
        with:
          name: resultats_test

      - name: Generate Output from Cypress Result
        id: set-output
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"

      - name: Add Badge to README
        uses: ./.github/actions/resultats_test
        with:
          resultats_test: ${{ steps.set-output.outputs.cypress_outcome }}

      - name: Commit and Push Changes to README
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Alejandro"
          author_email: "alemeco2005@gmail.com"
          message: "Afegir badge de Cypress"
          add: "."
          push: true

  deploy_job:
    runs-on: ubuntu-latest
    needs:
      - add_badge_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=$VERCEL_TOKEN --yes

  send_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send message to Telegram
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_ID_USER }}" \
          -d "text=Se ha realizado un push en la rama main"